version: 3

tasks:
  default:
    - task: fmt
    - task: lint
    - task: test

  init:
    desc: Init environment.
    cmds:
      - pre-commit install --install-hooks
      - pre-commit install --install-hooks --hook-type commit-msg

  update:
    desc: Update environment.
    cmds:
      - pre-commit autoupdate

  fmt:
    desc: Run formatters.
    cmds:
      - pre-commit run -a prettier

  lint:
    desc: Run linters.
    cmds:
      - pre-commit run -a markdownlint-cli2
      - pre-commit run -a yamllint
      - pre-commit run -a ansible-lint

  test:
    desc: Run tests.
    cmds:
      - molecule test
