- name: Fail when OS family not supported and no override configured
  when: >-
    (awscli_os_pkgs | length < 1)
    and (ansible_os_family | lower not in awscli_os_families)
  fail:
    msg: The target OS family is not Debian nor RedHat. Use var 'awscli_os_pkgs'.

- name: Include vars depending on OS family and override
  when: (awscli_os_pkgs is not iterable) or (awscli_os_pkgs | length < 1)
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "os-{{ ansible_os_family | lower }}.yaml"
      paths:
        - vars

- name: Install OS packages
  package:
    name: "{{ awscli_os_pkgs }}"
    state: present
  become: true

- name: Check if AWS CLI in the correct version is installed
  shell: |
    if ! aws --version | grep -c "aws-cli/{{ awscli_version }}"; then
      echo status=changed
    fi
  register: task
  changed_when: "'status=changed' in task.stdout"
  notify:
    - "{{ role_name }} : Download archive to tmp"
    - "{{ role_name }} : Create temporary dir for unpacked archive"
    - "{{ role_name }} : Unarchive archive to temporary dir"
    - "{{ role_name }} : Execute install script"
    - "{{ role_name }} : Check if install succeeded"

- name: Add init block to `~/.profile`
  blockinfile:
    path: ~/.profile
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      complete -C '/usr/local/bin/aws_completer' aws
      export PATH=/usr/local/aws/bin:$PATH
