# ------------------------------------------------------------------------------


- name: Fail when OS family not supported and no override configured
  when: >-
    (awscli_os_pkgs | length < 1) and
    (ansible_os_family | lower not in awscli_os_families)
  fail:
    msg: The target OS family is not Debian nor RedHat. Use var 'awscli_os_pkgs'.

- name: Include vars depending on OS family and override
  when: (awscli_os_pkgs is not iterable) or (awscli_os_pkgs | length < 1)
  include_vars: '{{ lookup("first_found", params) }}'
  vars:
    params:
      files:
        - os-{{ ansible_os_family | lower }}.yaml
      paths:
        - vars

- name: Install OS packages
  package:
    name: '{{ awscli_os_pkgs }}'
    state: present
  become: true


# ------------------------------------------------------------------------------


- name: Check AWS CLI status
  shell: |
    export PATH=/usr/local/aws/bin:$PATH
    if ! aws --version | grep -c aws-cli/{{ awscli_version }}; then
      echo 'install required'
    fi
  register: awscli_status
  changed_when: '"install required" in awscli_status.stdout'


# ------------------------------------------------------------------------------


- name: Download archive to tmp
  when: '"install required" in awscli_status.stdout'
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ awscli_version }}.zip
    dest: /tmp/awscli-{{ awscli_version }}.zip
  become: true

- name: Create temporary dir for unpacked archive
  when: '"install required" in awscli_status.stdout'
  file:
    path: /tmp/awscli-{{ awscli_version }}
    state: directory
  become: true

- name: Unarchive archive to temporary dir
  when: '"install required" in awscli_status.stdout'
  unarchive:
    src: /tmp/awscli-{{ awscli_version }}.zip
    dest: /tmp/awscli-{{ awscli_version }}/
    remote_src: true
  become: true

- name: Execute install script
  when: '"install required" in awscli_status.stdout'
  shell: |
    export PATH=/usr/local/aws/bin:$PATH
    if command -v aws &> /dev/null; then
      /tmp/awscli-{{ awscli_version }}/aws/install --update
    else
      /tmp/awscli-{{ awscli_version }}/aws/install
    fi
  become: true


# ------------------------------------------------------------------------------


- name: Ensure that AWS CLI is installed
  shell: |
    export PATH=/usr/local/aws/bin:$PATH
    if ! aws --version | grep -c aws-cli/{{ awscli_version }}; then
      exit 1
    fi
  changed_when: false


# ------------------------------------------------------------------------------
