- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get installed version
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          export PATH=/usr/local/bin:$PATH
          if command -v aws &> /dev/null; then
            aws --version | sed -E 's/aws-cli\/(.+) Python.*/\1/'
          fi
        executable: /usr/bin/bash
      register: get_installed_version
      changed_when: false

    - name: Set installed version
      ansible.builtin.set_fact:
        installed_version: >-
          {{ get_installed_version.stdout | regex_search(".+\..+\..+") }}

    - name: Verify installed version correct
      ansible.builtin.assert:
        that:
          - installed_version == "2.15.51"
        fail_msg: >-
          `installed_version` is "{{ installed_version }}", but must be "2.15.51".
