- name: Converge
  hosts: all

  pre_tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: trallnag.aws_cli
      vars:
        aws_cli__version: latest
