- name: Install APT dependencies
  apt:
    name:
      - libc6
      - groff
      - less
      - unzip
      - curl
    state: present
  become: true

- name: Download archive to tmp
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ awscli_version }}.zip
    dest: /tmp/awscli-{{ awscli_version }}.zip
  become: true

- name: Create temporary dir for unpacked archive
  file:
    path: /tmp/awscli-{{ awscli_version }}
    state: directory
  become: true

- name: Unarchive archive to temporary dir
  unarchive:
    src: /tmp/awscli-{{ awscli_version }}.zip
    dest: /tmp/awscli-{{ awscli_version }}/
    remote_src: true
  become: true

- name: Execute install script
  shell: |
    if command -v aws &> /dev/null; then
      /tmp/awscli-{{ awscli_version }}/aws/install --update
    else
      /tmp/awscli-{{ awscli_version }}/aws/install
    fi
  become: true

- name: Check if install succeeded
  shell: |
    if ! aws --version | grep -c "aws-cli/{{ awscli_version }}"; then
      exit 1
    fi
