- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
      changed_when: false

  tasks:
    - name: Include trallnag.awscli
      include_role:
        name: trallnag.awscli
