name: CI

#
# Primary workflow for continues integration.
#

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master, dev]
  schedule:
    - cron: 4 15 * * 6 # Every Saturday at 15:04.

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - run: poetry install

      - run: poetry run poetry run molecule test --all

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - run: poetry install

      - run: poetry run ansible-lint
