name: CI

#
# The primary workflow for continues integration.
#

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - "**"
  schedule:
    # At 04:10 on Monday.
    - cron: 10 4 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  skip:
    name: Skip
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    outputs:
      skip: ${{ steps.skip.outputs.should_skip }}
    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          concurrent_skipping: always
          skip_after_successful_duplicate: true

  fix-check-test:
    needs: skip
    if: needs.skip.outputs.skip != 'true'
    name: Fix & Check & Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      UV_PYTHON_PREFERENCE: only-system
      UV_PYTHON_DOWNLOADS: never
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0

      # Used by mise to verify tools with aqua backend.
      - name: Set up Cosign
        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2

      # Extract subset of mise tools configuration to separate files which are
      # used in subsequent steps as part of cache keys.
      - name: Extract mise tools
        id: extract-mise-tools
        run: |
          mkdir -p .tmp
          pipx=.tmp/mise-pipx.toml
          echo "pipx=$pipx" | tee -a $GITHUB_OUTPUT
          grep -F -e pipx mise.toml | tee $pipx

      # Init pip cache dir to prevent failure of workflow run with error about
      # cache folder not existing and that the cache step should be removed.
      - name: Init pip cache dir
        run: mkdir -p ~/.cache/pip

      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: pyproject.toml

      - name: Set up Astral uv
        uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6.3.0
        with:
          enable-cache: true
          cache-suffix: fix-check-test
          cache-dependency-glob: |
            uv.lock
            ${{ steps.extract-mise-tools.outputs.pipx }}

      - name: Cache pre-commit cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: >-
            pre-commit cache dir
            ${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up mise
        uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
        env:
          MISE_JOBS: 1
          MISE_VERBOSE: 1
        with:
          install: true
          cache: true
          cache_key_prefix: ${{ steps.set-up-python.outputs.python-version }}

      - name: Run recipes that fix stuff
        run: just fix

      - name: Run recipes that check stuff
        run: just check

      - name: Commit and push changes
        if: |
          cancelled() == false &&
          github.actor != 'dependabot[bot]' &&
          github.ref_type != 'tag' &&
          startsWith(github.ref, 'refs/head/renovate/') == false
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: "ci: Apply automatic improvements"
          commit_options: --no-verify --signoff

      - name: Run tests
        run: just test
