name: Import

#
# Imports role to Ansible Galaxy.
#
# Useful for performing the import without creating a new GitHub release.
#

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  import:
    name: Import
    runs-on: ubuntu-latest
    environment:
      name: Galaxy
      url: https://galaxy.ansible.com/ui/standalone/roles/trallnag/aws_cli
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: pyproject.toml

      - name: Set up Astral uv
        uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6.3.0
        with:
          enable-cache: true
          cache-suffix: release
          cache-dependency-glob: |
            uv.lock

      - name: Import to Ansible Galaxy
        run: >-
          uv run ansible-galaxy role import
          --server https://galaxy.ansible.com/api/
          --token "${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}"
          --role-name aws_cli
          "${{ github.event.repository.owner.login }}"
          "${{ github.event.repository.name }}"
