name: Pre-Commit Updates

#
# Updates pre-commit hooks to the latest available versions.
#
# Opens a pull request if any updates are available.
#

on:
  workflow_dispatch:
  schedule:
    - cron: 34 12 4 * * # Runs at 12:34 (UTC), on day 4 of the month.

jobs:
  pre-commit-updates:
    name: Pre-Commit Updates
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add entries to PATH
        run: |
          echo "$HOME/.local/bin" | tee -a "$GITHUB_PATH"

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Update pre-commit hook(s)
        run: pre-commit autoupdate

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: pre-commit-update
          title: "build(deps): Update pre-commit hook(s)"
          commit-message: "build(deps): Update pre-commit hook(s)"
          delete-branch: true
